name: sevenclass
description: Online classmates rooms

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.6+2
  dio: ^3.0.9
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  sqflite: ^1.2.1
  firebase_core: ^0.4.4+2
  firebase_crashlytics: ^0.1.3
  google_sign_in: ^4.1.4
  flutter_svg: ^0.17.2
  sliding_up_panel: ^1.0.0
  flutter_stetho: ^0.5.2
  fluttertoast: ^3.1.3
  permission_handler: ^4.3.0
  qr_code_scanner: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/intro/illustration1.png
    - assets/images/intro/illustration2.png
    - assets/images/intro/illustration3.png
    - assets/images/intro/illustration4.png
    - assets/images/icons/google.svg
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf